steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - '-c'
      - >-
        docker pull gcr.io/$PROJECT_ID/github.com/richds/rp-flask-api:latest ||
        exit 0
    entrypoint: bash
  - name: gcr.io/cloud-builders/docker
    script: >
      docker build -t gcr.io/$PROJECT_ID/github.com/richds/rp-flask-api:latest
      --cache-from gcr.io/$PROJECT_ID/github.com/richds/rp-flask-api:latest .
    automapSubstitutions: true
  - name: gcr.io/cloud-builders/docker
    args:
      - run
      - '-d'
      - '--rm'
      - '--name=test_container'
      - 'gcr.io/$PROJECT_ID/github.com/richds/rp-flask-api:latest'
  - name: gcr.io/cloud-builders/docker
    args:
      - exec
      - test_container
      - pytest
      - '-sv'
images:
  - 'gcr.io/$PROJECT_ID/github.com/richds/rp-flask-api:latest'
